source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               resources/

# Temporarily setting these to force Java 17 compatibility during the build.
# These will be removed when the global properties are set to 17.
javacSource=17
javacTarget=17